# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Antonio Flores Montoya'
tagline:          'Personal Page'
description:      'Computer Scientist'
url:              https://aeflores.github.io
baseurl:          /

author:
  name:           'Antonio Flores Montoya'
  url:            https://aeflores.github.io

#paginate:         1

# Custom vars
version:          2.1.0

#github:
#  repo:           https://github.com/poole/hyde
  
# Gems
plugins_dir:
  - jekyll-paginate
  - jekyll-gist
